version: '3'
services:
  server:
    image: drone/drone:1
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${HOST}
      DRONE_SERVER_PROTO: ${PROTO}
      DRONE_USER_FILTER: ${DRONE_USER}
      DRONE_USER_CREATE: username:${DRONE_USER},admin:true
  runner:
    image: drone/drone-runner-docker:1
    ports:
      - 3000:3000
    restart: always
    container_name: runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: server
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: runner1
      DRONE_UI_USERNAME: ${DRONE_UI_USERNAME}
      DRONE_UI_PASSWORD: ${DRONE_UI_PASSWORD}
